name: conceptgraph
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  - xformers
dependencies:
  - python=3.10
  - pip=24.2
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - cuda-toolkit=12.1.0
  - cuda-nvcc=12.1
  - cuda=12.1.0
  - cuda-tools=12.1.0
  - cuda-version=12.1
  - cuda-command-line-tools=12.1.0
  - cuda-compiler=12.1.0
  - cuda-runtime=12.1.0
  - gxx=12.1.0
  - faiss-cpu=1.7.4
  - mkl=2021
  - blas=1.0=mkl
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu121
    - torch==2.4.1+cu121
    - torchvision==0.19.1+cu121
    - pytorchvideo==0.1.5
    # - pytorch3d==0.7.8 -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu121_pyt241/download.html
  - pip:
    - xformers==0.0.28
    - transforms3d==0.4.2
    - open3d==0.19.0
    - matplotlib==3.8.2
    - opencv-python==4.11.0.86
    - opencv-contrib-python==4.11.0.86
    - huggingface_hub==0.25.2
    - ultralytics==8.3.151
    - distinctipy==1.3.4
    - open-clip-torch==2.7.0
    - supervision==0.13.0
    - fairscale==0.4.13
    - git+https://github.com/krrish94/chamferdist.git
    - git+https://github.com/WangYixuan12/urdfpy.git
    - git+https://github.com/WangYixuan12/yixuan_utilities.git
    - git+https://github.com/facebookresearch/co-tracker.git
    - git+https://github.com/WangYixuan12/XMem.git
    - git+https://github.com/facebookresearch/segment-anything.git
    - git+https://github.com/gradslam/gradslam.git@conceptfusion
    - git+https://github.com/xinyu1205/recognize-anything.git
    - git+https://github.com/IDEA-Research/GroundingDINO.git